# Generated by Django 2.2.9 on 2020-02-18 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('uID', models.AutoField(primary_key=True, serialize=False)),
                ('isOwner', models.BooleanField(null=True)),
                ('uName', models.CharField(max_length=50)),
                ('uPhone', models.CharField(max_length=11, unique=True)),
                ('uBirthDay', models.CharField(max_length=8)),
                ('uImage', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'USER',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('sID', models.AutoField(primary_key=True, serialize=False)),
                ('sName', models.CharField(max_length=50)),
                ('sPhone', models.CharField(max_length=50)),
                ('uID', models.ForeignKey(db_column='uID', on_delete=django.db.models.deletion.CASCADE, to='Maria_Membership.Info')),
            ],
            options={
                'db_table': 'STORE',
            },
        ),
        migrations.CreateModel(
            name='RMENU',
            fields=[
                ('mID', models.AutoField(primary_key=True, serialize=False)),
                ('mName', models.CharField(max_length=45)),
                ('mDesc', models.CharField(max_length=45, null=True)),
                ('mPrice', models.IntegerField()),
                ('mImage', models.CharField(max_length=200)),
                ('sID', models.ForeignKey(db_column='sID', on_delete=django.db.models.deletion.CASCADE, to='Maria_Membership.Store')),
            ],
            options={
                'db_table': 'MENU',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('americano', models.IntegerField()),
                ('latte', models.IntegerField()),
                ('smoothy', models.IntegerField()),
                ('total', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maria_Membership.Info')),
            ],
            options={
                'db_table': 'menu_info',
            },
        ),
    ]
